services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - backend
    restart: always
    environment:
      DOMAINS: "ticket-system.umch.de -> https://ticket-system.umch.de:5000"  

  backend:
    container_name: umch-ticket-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map container port 3000 to host port 3000
    volumes:
      - /usr/src/app/node_modules # Avoid overwriting node_modules
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - mongodb # Ensure MongoDB starts before the backend
    restart: always # Restart container if it crashes
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.backend.rule=Host(`ticket-system.umch.de`)" # Add your domain here
    #  - "traefik.http.services.backend.loadbalancer.server.port=5000" # Replace "<PORT>" with the port your API is listening to.
    #  - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

  mongodb:
    container_name: umch-mongodb
    image: mongo:6.0 # Use the official MongoDB image
    ports:
      - "27017:27017" # Map MongoDB port 27017
    volumes:
      - mongodb-data:/data/db # Persist MongoDB data

volumes:
  mongodb-data: # Define a named volume for MongoDB data persistence
